title: UmutFaruk Docs
description: Welcome to UmutFaruks Docs Site
remote_theme: just-the-docs/just-the-docs

url: https://cenairaclub.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
